name: Honeypot
main: com.argo.bukkit.honeypot.Honeypot
url: http://dev.bukkit.org/server-mods/Honeypot/
version: 1.4.2.1 ColeBans Edition
author: Argomirr,morganm,dog.big
depend: [ColeBans]
softdepend: [MCBans, WorldEdit]
commands:
 honeypot:
  description: Enables Op's to create honeypots by right clicking a block with a wooden axe.
  usage: /<command>
  aliases: [hp]
